// flow-typed signature: d43e51f507cb8d2f85b355cedb9e935e
// flow-typed version: <<STUB>>/remark-breaks_v^1.0.1/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-breaks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-breaks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-breaks/index' {
  declare module.exports: $Exports<'remark-breaks'>;
}
declare module 'remark-breaks/index.js' {
  declare module.exports: $Exports<'remark-breaks'>;
}
